### ISSUE TITLE
Order of root records

### ISSUE THREAD

**Issue by ZAYEC77** [paulzi/yii2-nested-sets#1]
Hello, can I make custom ordering of root records with your behavior?

**Comment by paulzi** [comment]
With `NestedSetsQueryTrait`:
```php
$orderedRoots = Node::roots()->orderBy(['column' => SORT_ASC])->all();
```

**Comment by ZAYEC77** [comment]
@paulzi have I add custom column for this purposes?

**Comment by paulzi** [comment]
Yes of course. Please read Yii2 documentation:
http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html
