### ISSUE TITLE
Повторяющееся значение ключа нарушает ограничение уникальности "category_pkey"

### ISSUE THREAD

**Issue by wtfmrpresident** [paulzi/yii2-nested-sets#10]
Добрый день!
Очень странная ошибка вылезает исключительно при первом сохранении

`SQLSTATE[23505]: Unique violation: 7 ОШИБКА: повторяющееся значение ключа нарушает ограничение уникальности "category_pkey" DETAIL: Ключ "(id)=(1)" уже существует. The SQL being executed was: INSERT INTO "module_category" ("name", "slug", "sort_order", "status", "created_at", "updated_at", "lft", "rgt", "depth") VALUES ('Пылесосы', 'pylesosy', 1, FALSE, 1531748095, 1531748095, 2, 3, 1) RETURNING "id"
`

Очень странные дела, он как будто пытается insert категорию, которая находится в _node

Сохранение происходит как написано в мануале:

```
$parent = Category::findOne($this->parent_id);
// ...
$category->appendTo($parent);
$category->save();
```

Ошибка возникает именно при самом первом сохранении после миграции.
PS: в миграции идет вставка "root" категории
PSS: https://monosnap.com/file/qHElE2SvMh2GCYsvrPUYNDjrA74U6t

**Comment by paulzi** [comment]
Скорее всего у вас на поле id стоит sequence с неверным значением. Вам нужно сделать в базе
```
setval('module_category_id_seq', 2)
```
где 2 свободный id-шник
