### ISSUE TITLE
Мультидерево, проблема обновления элемента

### ISSUE THREAD

**Issue by defk** [paulzi/yii2-nested-sets#11]
Доброго дня!

Есть таблица с множественными nested sets в ней.

При попытке обновить (не добавить!) отдельную запись, которая является вершиной дерева - происходит ошибка, выражающаяся в том, что treeAttribute оказывается равен id обновляемого элемента, а не id дерева. Хотя id дерева уходит правильный.

Проблема возникает потому, что treeChange в beforeUpdate заполняется только если изменено treeAttribute. Но, мне то надо просто имя корня дерева поменять.

Если строку $this->treeChange = $this->owner->getAttribute($this->treeAttribute); вынести из if, в который она обернута - код начинает корректно работать.

**Comment by defk** [comment]
Либо необходимо сделать дополнительную проверку на $leave->getIsNewRecord() == false перед тем, как делать $leave->makeRoot()

**Comment by paulzi** [comment]
Правильно, я понимаю, что вы хотите сделать существующий НЕ корневой узел, корневым, и при попытке это сделать, у вас не сохраняется заданный treeAttribute?

**Comment by defk** [comment]
нет, я делаю update существующего корневого элемента.

**Comment by paulzi** [comment]
treeChange проставляется только если вызвать makeRoot(), зачем делать makeRoot при update? У вас меняется treeAttribute?

**Comment by defk** [comment]
Нет, я стремился свести к минимуму разницу между созданием и обновлением.
Сейчас там лишний if из-за этого.
А вот если кому-то реально понадобится сперва insert, а уже потом сделать makeRoot()?
