### ISSUE TITLE
Problem with documentation

### ISSUE THREAD

**Issue by elmys** [paulzi/yii2-nested-sets#13]
All right with extension? 
Why in this structure:
**-Countries
--England
--New Zealand**

After **Auckland**->appendTo(**New Zeland**) if i checking **Auckland**'s  parent, than this it's null?
But parent of **NewZealand** it's **Countries** (true).

_Yii 2.0.15.1_

**Comment by paulzi** [comment]
Please provide sample code.

**Comment by elmys** [comment]
1. _Init table with 3 records_
Apply migration for add columns lft...tree, then:
```
$rootObject = new DictObject([
            'id' => '1',
            'name_full' => 'root'
        ]);
        $rootObject->makeRoot()->save();
        $others = DictObject::find()->where(['>', 'id', 1])->all();
        foreach ($others as $other) {
            $other->appendTo($rootObject)->save();
        }
```
[results](https://drive.google.com/file/d/1tvPqfMCd-zW-PGxQU6LMgPyZIPvbWbPa/view?usp=drivesdk)
2. _Add new child for 'Корпус 1':_ 
$model = new DictObject(['name_full' => 'к11']);
$parent = DictObject::findOne(['id' => 3]);
$model->appendTo($parent)->save();
[result](https://drive.google.com/file/d/1XavW9NflhRk5C8VUXQUKD75MMV3zBoZc/view?usp=drivesdk)

3. _On testing gridview parent к11 = null:_
[
                'label' => Yii::t('app', 'Parent Object'),
                'value' => function ($value) {
                    return $value->parent->name_full;
                }
            ],
[result](https://drive.google.com/file/d/11nHW_tolH5IcfBCBsFGmeSt4UHdKNdB0/view?usp=drivesdk)

**Comment by paulzi** [comment]
Why Корпус 1-3 has left = right = 4 in first step? It is wrong!
How were these nodes added?

Каким образом были добавлены узлы «Корпус 1-3»? У них неверные значения left и right.

**Comment by elmys** [comment]
In foreach cycle on first step (because, my task in rebuild existing records with this extension).

**Comment by paulzi** [comment]
What initial data in DB before the first step run?

**Comment by elmys** [comment]
Just columns id and full_name without ext columns (lft .. tree)

**Comment by paulzi** [comment]
As I understand it DictObject has attributes `left` and `right`.
By that line: `$others = DictObject::find()->where(['>', 'id', 1])->all();` you are find some models in this models (and this table).
That's why I'm asking what are the values of the attributes tree/left/right/depth?

**Comment by elmys** [comment]
Default, same as in migration = 0:
$this->addColumn('dict_object', 'tree', $this->integer());
        $this->addColumn('dict_object', 'lft', $this->integer()->defaultValue(0));
        $this->addColumn('dict_object', 'rgt', $this->integer()->defaultValue(0));
        $this->addColumn('dict_object', 'depth', $this->integer()->defaultValue(0));
        $this->createIndex('lft', 'dict_object', ['tree', 'lft', 'rgt']);
        $this->createIndex('rgt', 'dict_object', ['tree', 'rgt']);

**Comment by paulzi** [comment]
![default](https://user-images.githubusercontent.com/9402208/49379885-5eb98c80-f721-11e8-8558-662c6e59de93.png)
This is initial data, correct?

**Comment by elmys** [comment]
yes (before foreach launching)
![phpstorm64_2018-12-03_17-37-49](https://user-images.githubusercontent.com/5611459/49380511-f075c980-f722-11e8-8a30-8412f2758e81.png)

**Comment by paulzi** [comment]
The problem is that you are trying to store input plain data in a tree-structured table. Because of this, an error occurs, because from the point of view of behavior, all nodes that you currently are all roots with a single tree attribute = null. I't is wrong input data.
If you want to fill the tree-structure, store the input data in another table, or make the nodes real roots with different tree attribute:
![default](https://user-images.githubusercontent.com/9402208/49383887-da6c0700-f72a-11e8-8e1d-ab76ce7eef65.png)
