### ISSUE TITLE
Определение родителя для новых узлов

### ISSUE THREAD

**Issue by phrakon** [paulzi/yii2-nested-sets#14]
Здравствуйте.
Вопрос такой. Имеется уже существующее дерево. Я хочу добавить к уже существующему элементу новый:

$parentItem = Item::findOne(10);
$newItem = new Item(['name' => 'Новый элемент']);
$newItem->appendTo($parentItem);

При этом я не сохраняю $newItem элемент.
Если я попытаюсь узнать родительский элемент путем
$parent = $newItem->parent;
то там естественно ничего нет. Так как у нас в элементе $newItem еще нет lft+rgt атрибутов
Однако в поведении в защищенном свойстве node он присутствует.

Как вы считаете, будет нормальным переопределить метод  getParents таким образом, что если
$this->owner новая запись и если установлено свойство node, то вернуть цепочку родителей для node, иначе действовать как и работало?

**Comment by phrakon** [comment]
Ну и вообще, как вы смотрите на улучшение работы поведения с новыми моделями?

**Comment by paulzi** [comment]
Здравствуйте! Думаю что до тех пор пока не произойдёт сохранение, поведения многих методов будет невозможным к реализации. Например, `isRoot()` сейчас определяется по left = 1, а так как эти атрибуты заполняются после сохранения, то и соответственно работать не будет как надо.
Это относится к большинству методов, и нормально реализовать можно разве что для получения родителей.
Поэтому логика работы методов чётко определена только для сохранённых моделей. До тех пор пока состояние не сохранено, узел числится на прежней позиции.
