### ISSUE TITLE
Нужна помощь по выводу дерева-меню

### ISSUE THREAD

**Issue by asder117** [paulzi/yii2-nested-sets#16]
Доброе время суток. А как можно дерево в виде меню вывести на форму?

**Comment by paulzi** [comment]
Можно, только это уже визуал, тут функционал)

**Comment by asder117** [comment]
Спасибо. "только это уже визуал" Так я про это и спрашивал. Нет примера реализации?

**Comment by asder117** [comment]
> Можно, только это уже визуал, тут функционал)

**Comment by paulzi** [comment]
Попробуйте тут глянуть:
https://github.com/voskobovich/yii2-tree-manager

Просто визуализация может быть хоть на `<ul> <li>` рекурсивно

**Comment by asder117** [comment]
Спасибо.
