### ISSUE TITLE
Построение дерева на форме

### ISSUE THREAD

**Issue by asder117** [paulzi/yii2-nested-sets#17]
Доброго времени суток. Столько решений по деревьям но нигде не могу найти функционал его построения. Картиком все вроде строиться. Вопрос другой как обеспечит поведение при выборе элемента дерева. к примру выбираешь элемент а по нему выводится рядом инфа. У картика это ничего не расписано и на форумах 0. Может у вас что-то есть раз переписывали под себя его

**Comment by paulzi** [comment]
Добрый день, с такими вопросами лучше в stackoverflow.
