### ISSUE TITLE
Can not create more than one root.

### ISSUE THREAD

**Issue by AlimovRoostam** [paulzi/yii2-nested-sets#2]
`
 public function behaviors() {
        return [
            [
                'class' => NestedSetsBehavior::className(),
                'treeAttribute' => 'tree',
            ],
        ];
    }
`

**Comment by paulzi** [comment]
Show migration, code and error logs.
If the attribute is not specified, it will be automatically set to the primary key. Accordingly, the base should be no record with this primary key.

**Comment by AlimovRoostam** [comment]
Миграции

`'id'    => $this->primaryKey(),
'tree'  => $this->integer(),
'lft'   => $this->integer()->notNull(),
'rgt'   => $this->integer()->notNull(),
'depth' => $this->integer()->notNull(),
'title'   => $this->string(255)->notNull()->unique(),
`

`
$this->createIndex('lft', '{{%pages}}', ['tree', 'lft', 'rgt']);
$this->createIndex('rgt', '{{%pages}}', ['tree', 'rgt'])
`

_________________________________________
Код

`
 if (Yii::$app->request->isPost && !empty(Yii::$app->request->post('Pages'))) {
            $post = Yii::$app->request->post('Pages');
            $model->title = $post['title'];

            $model->makeRoot()->save();

            return $this->redirect(['view', 'id' => $model->id]);


        }
`
