### ISSUE TITLE
Ошибка в методе populateTree

### ISSUE THREAD

**Issue by ilgiz-badamshin** [paulzi/yii2-nested-sets#4]
Здравствуйте.
$depth является входящим параметром: 
`public function populateTree($depth = null)`
но потом он переопределяется в цикле foreach:
`$depth = $node->getAttribute($this->depthAttribute);`
После этого перестает работать условие: 
```
 } elseif ($depth === null) {
    $node->populateRelation('children', []);
}
```
Как следствие, для элементов дерева, у которых нет дочерних элементов, создается дополнительный запрос в базу на их поиск. 
Так было задумано или в цикле надо использовать другую переменную?
То же самое и для NestedIntervalsBehavior.

**Comment by ilgiz-badamshin** [comment]
И второй вопрос, нужно ли это условие  `} elseif ($depth === null) {`?
Если я решил построить дерево с $depth = 2 (populateTree(2)), а потом рекурсивно начал его обходить по children-ам,  то я обойду все дерево, а не только 2 уровня.

**Comment by paulzi** [comment]
Доброго времени суток! Спасибо, за информацию, действительно ошибочно использовал переменную `$depth`.
По поводу этого условия, оно было необходимо в случае, если у узла нет ни одного ребёнка, в таком случае оно помогало в любом случае задать пустое множество детей, хотя конечно некорректно это делал. Исправил.
По поводу рекурсивного обхода, вы конечно можете обходить любое число уровней, но если вы сделали `populateTree(2)`, а в рекурсии пошли запрашивать третий уровень children, то в этом случае пойдёт дополнительные запросы в БД, а если же запросить нужное число уровней и не выходить за их пределы - дополнительных запросов не будет, всё вытянется единым запросом.

**Comment by paulzi** [comment]
Ну и в тестах отразил данный вариант событий.

**Comment by ilgiz-badamshin** [comment]
Спасибо за оперативность. 
По второму вопросу получается, что надо вызывать populateTree с нужным уровнем и в рекурсии дополнительно проверять уровень.

**Comment by paulzi** [comment]
Вопрос в том, что вам нужно. Если вам нужно построить всё дерево, то и запрашивайте всё дерево простым вызовом `populateTree()`. Если вы точно знаете, что будете показывать только 3 уровня пользователю не больше, то лучше вызываете `populateTree(3)`, и проверяйте у себя в рекурсии уровень, иначе вы покажете больше 3 уровней пользователю.
То есть юзкейс в основном такой:
1) Простой пример - дерево комментариев к посту который показываем сразу. Вызываем `populateTree()`, один запросом выгребаем всех детей и простой рекурсией показываем все комментарии.
2) Пример с подгрузкой уровней через ajax. Показываем только комментарии верхнего уровня, а если хотим смотреть ответы на них нажимаем "посмотреть". В таком случае можно сделать `populateTree(1)`, хотя не обязательно, так как первый уровень детей вы сразу получите при обращению к `->children->`.
3) Система комментариев как на liveinternet - показываем только 5 уровней комментариев, если нужно больше пользователь щёлкает ссылку, и данная ветка раскрывается до конца. Тут идеально пригодится `populateTree(5)`.

То есть `populateTree()` просто запрашивает информацию о потомках нужного числа уровней одним запросом и соответствующим образом заполняет релейшен `children`, если вы попытаетесь получить children для уровня, который не запрашивали, просто произойдёт ещё один запрос к БД.
