### ISSUE TITLE
PopulateTree и связанные таблицы

### ISSUE THREAD

**Issue by ilgiz-badamshin** [paulzi/yii2-nested-sets#5]
Не думали над реализацией выборки зависимых данных во время построения дерева? 
Например есть дерево пользовательских сообщений. Нужно пострить дерево и для каждого сообщения указать его пользователя. 
Сейчас для каждого элемента будет вызван дополнительный запрос в таблицу пользователей. 
Можно добавить входящий параметр $with и поправить выборку $nodes:
`$nodes = $this->getDescendants($depth)->with($with)->all();`

**Comment by paulzi** [comment]
Спасибо за предложение, сделаем)

**Comment by Matvik** [comment]
Есть подвижки по данному вопросу? Очень нужно, иначе много запросов. Пока только кеширование спасает.

**Comment by Matvik** [comment]
Спасибо, а можно добавить аналогичный апгрейд в другие поведения с единым API? В частности. я использую yii2-materialized-path и yii2-adjacency-list. Ну и тогда уже и yii2-auto-tree

**Comment by paulzi** [comment]
Да, конечно, обязательно добавлю в течение нескольких дней.

**Comment by Matvik** [comment]
Спасибо, ждем

**Comment by Matvik** [comment]
Только еще нужно обновить yii2-auto-tree:
[https://github.com/paulzi/yii2-auto-tree/issues/5](https://github.com/paulzi/yii2-auto-tree/issues/5)
