### ISSUE TITLE
Перемещение узла не работает

### ISSUE THREAD

**Issue by asminog** [paulzi/yii2-nested-sets#6]
-root
--first
--second

first->appendTo(second)->save();

**Comment by paulzi** [comment]
Я написал тест для Вашей ситуации, баг не подтвердился. Можете сами запустить в phpUnit.
```php
public function testIssue()
    {
        (new TestMigration())->up();
        $dataSet = new ArrayDataSet(require(__DIR__ . '/data/issue.php'));
        $this->getDatabaseTester()->setDataSet($dataSet);
        $this->getDatabaseTester()->onSetUp();

        $node = Node::findOne(2);
        $this->assertTrue($node->appendTo(Node::findOne(3))->save());

        $node = MultipleTreeNode::findOne(2);
        $this->assertTrue($node->appendTo(MultipleTreeNode::findOne(3))->save());

        $dataSet = $this->getConnection()->createDataSet(['tree', 'multiple_tree']);
        $expectedDataSet = new ArrayDataSet(require(__DIR__ . '/data/test-issue.php'));
        $this->assertDataSetsEqual($expectedDataSet, $dataSet);
    }
```
Исходные данные:
```php
return array(
    'tree' => array(
        array('id' => '1','lft' => '1','rgt' => '6','depth' => '0','slug' => 'r1'),
        array('id' => '2','lft' => '2','rgt' => '3','depth' => '1','slug' => 'n1'),
        array('id' => '3','lft' => '4','rgt' => '5','depth' => '1','slug' => 'n2'),
    ),
    'multiple_tree' => array(
        array('id' => '1','tree' => '1','lft' => '1','rgt' => '6','depth' => '0','slug' => 'r1'),
        array('id' => '2','tree' => '1','lft' => '2','rgt' => '3','depth' => '1','slug' => 'n1'),
        array('id' => '3','tree' => '1','lft' => '4','rgt' => '5','depth' => '1','slug' => 'n2'),
    )
);
```

Результат:
```php
return array(
    'tree' => array(
        array('id' => '1','lft' => '1','rgt' => '6','depth' => '0','slug' => 'r1'),
        array('id' => '2','lft' => '3','rgt' => '4','depth' => '2','slug' => 'n1'),
        array('id' => '3','lft' => '2','rgt' => '5','depth' => '1','slug' => 'n2'),
    ),
    'multiple_tree' => array(
        array('id' => '1','tree' => '1','lft' => '1','rgt' => '6','depth' => '0','slug' => 'r1'),
        array('id' => '2','tree' => '1','lft' => '3','rgt' => '4','depth' => '2','slug' => 'n1'),
        array('id' => '3','tree' => '1','lft' => '2','rgt' => '5','depth' => '1','slug' => 'n2'),
    )
);
```

Для уточнения ошибки, предоставьте схему данных, тестовые данные, скорее всего ошибка где-то там.

**Comment by asminog** [comment]
:) да схема у меня с UNSIGNED
CREATE TABLE `single_tree` (
  `id` int(11) NOT NULL,
  `lft` int(11) UNSIGNED NOT NULL,
  `rgt` int(11) UNSIGNED NOT NULL,
  `depth` int(11) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

без UNSIGNED работает

**Comment by paulzi** [comment]
Объясню. У меня требуется signed для оптимизации как раз такого перемещения узлов между собой (moveNode). У creocoder это делается путём сначала сдвига всех узлов от целевого вперёд, затем сдвига всех узлов обратно. При большом количестве узлов это может занимать большое кол-во времени.
В моей реализации перемещения производятся только узлов между целевыми, что может значительно сказаться на производительности, особенно при операциях в начале дерева. Но для этого нужно временное поле, и чтобы его не плодить, я решил сделать обязательным поле signed.
Ну и чтобы не быть голословным, я измерял производительность решения по сравнению с creocoder, и вот один из результатов:
```
Test 9. Move random in begin <4% (20 in 19657 nodes)
    Creocoder           200         24,312 ms   25,479 ms   6.3 MB
    PaulZi              140         218 ms      566 ms      5.5 MB 
```

**Comment by asminog** [comment]
Если бы требование signed было указано в описании -- это сэкономило бы мне пару часов дебага.

Классное расширение спасибо.

**Comment by paulzi** [comment]
Принял, укажу по возможности в README
