### ISSUE TITLE
Проблема с неверным расчетом с UNSIGNED атрибутами для depth

### ISSUE THREAD

**Issue by aquy** [paulzi/yii2-nested-sets#7]
Когда depth имеет тип int и выставлена опция UNSIGNED, что вполне верно для уровня вложенного списка, так как отрицательным он не может быть. Происходит неверный перерасчет при операциях обновления, а именно insertBefore appendTo insertAfter при этом создание новых элементов дерево проходит нормально, а вот редактирование нет

Позапускал тесты с 'depth' => Schema::TYPE_INTEGER . ' UNSIGNED NOT NULL',
они соответственно проваливаются

**Comment by paulzi** [comment]
Да, забыл указать в README что depth требуется SIGNED. Причины можно почитать тут:
https://github.com/paulzi/yii2-nested-sets/issues/6#issuecomment-296102619
Issue закрую когда укажу информацию в README.
