### ISSUE TITLE
Tree by status

### ISSUE THREAD

**Issue by loveorigami** [paulzi/yii2-nested-sets#8]
Пытаюсь прикрутить статус к категориям.
Но запутался с выборкой.

Есть меню в 3 уровня. 
У активного родителя 2 уровня "parent2" есть много детей. Дети часть скрыты, часть нет.

Запрос на построение меню такой
```php
$this->models = $parent->getDescendants()
    ->published()
    ->all();
```
Если я скрываю родителя, то он выдает мне нескрытых детей.
Пробовал через
```
 $parent->getLeaves()->published() // нескрытые дети тоже попадают в выборку
 $parent->getChildren()->published() // получаю родителей второго уровня. Третий отсутствует.
```
Как более рационально можно построить меню, в котором не учитываются дети, если родитель скрыт?

Спасибо

**Comment by paulzi** [comment]
Все методы - являются relation на основе ActiveQuery. В этих связях в YII2 не учитывается статус родителя, если вам нужна такая проверка, вы должны организовать ей самостоятельно, например:
```php
if ($parent->is_published) {
    $children = $parent->getDescendants()->published()->all();
} else {
    $children = [];
}
```
Как вариант, этот код можно оформить как метод getDescendantsPublished().

Но ещё раз повторю, стандартные релейшены в Yii2, не учитывают статус родителя, для поиска множества записей с with(), например классическая связка adjacency list:
```php
/**
 * @return \yii\db\ActiveQuery
 */
public function getChildren()
{
    return $this->hasMany(self::className(), ['parent_id' => 'id']);
}
```

**Comment by loveorigami** [comment]
Немного не понял ответ (или Вы мой вопрос ))) ).  Из двух уровневого дерева не проблема сделать вывод так как Вы написали.
У меня меню из трех уровней.
Первый уровень - 1 элемент (node 1.1)) )
`$node11 = Sample::findOne(['name' => 'node 1.1']);`
На втором уровне 10 родителей (node 1.2.1 - 1.2.10).
У каждого родителя 10 детей. ('node 1.2.1.1 - 1.2.10.10')

Я скрываю одного родителя (№ 10), но у меня все равно выводится 100 детей по этому запросу
$descendants = $node11->getDescendants()->published()->all(); // via query

Я понимаю, что сейчас мне нужно через foreach пройтись по всем 100 детям, у каждого узнать, скрыт его родитель или нет, и потом только его вывести.  А если уровня будет 4?

Мне не нравится такой подход, т.к. на каждую проверку надо делать запрос в бд.

Т.е., выбирая NestedSet, пытался уйти от  большого количества запросов в бд, а на деле при выводе получил еще больше.

Issue я создал, чтоб Вы, как автор, порекомендовали наиболее оптимальное решение по формированию дерева. Возможно есть какой-то метод в поведении, который я не правильно применяю, для облегчения нужной мне выборки.

Спасибо.

**Comment by paulzi** [comment]
Это проблема деревьев в целом (а не NestedSets и других). Решить описанную вами проблему можно двумя способами:
1) Либо при отключении родителя триггерами (или др. средствами) отключать также и детей.
2) Либо, да, делать foreach.
Сформировать такой SQL запрос стандартными средствами вряд ли получится - нужна поддержка рекурсивных запросов.

Наиболее оптимальное, с моей точки зрения, сделать так:
```php
function treeListData($node, $level = 0)
{
    $result = [];
    foreach ($node->children as $child) {
        if ($child->is_published) {
            $result[$child->id] = str_repeat('----', $level) . $child->name;
            $result = $result + treeListData($child, $level + 1);
        }
    }
    return result;
}

$node->populateTree(); // выгребаем всех детей одним запросом
var_dump(treeListData($node)); // рекурсивно обходим всех и выводим
```

**Comment by loveorigami** [comment]
Спасибо большое. То что нужно!
