### ISSUE TITLE
Trying to get properties via relation causes Invalid argument supplied for foreach() in BaseActiveRecord.setRelationDependencies

### ISSUE THREAD

**Issue by LyudmilaPetrova** [paulzi/yii2-nested-sets#9]
Got error:
`foreach ($product->category->parents as $parent) {
   ...
}`

Ok:
`foreach ($product->category->getParents()->all() as $parent) {
    ...
}`

Yii 2.0.14
PHP 7.1.15

**Comment by paulzi** [comment]
What's wrong? Please, provide a stack trace.

**Comment by LyudmilaPetrova** [comment]
2018-03-28 18:20:45 [192.168.83.1][1][i0oi9bc2ak0g03gou9slt3e9eq][error][yii\base\ErrorException:2] yii\base\ErrorException: Invalid argument supplied for foreach() in /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php:1732
Stack trace:
#0 /app/frontend/views/shop/catalog/product.php(20): shop\entities\Shop\Category->__get()
#1 /app/vendor/yiisoft/yii2/base/View.php(336): yii\web\View->unknown()
#2 /app/vendor/yiisoft/yii2/base/View.php(254): yii\web\View->renderPhpFile()
#3 /app/vendor/yiisoft/yii2/base/View.php(156): yii\web\View->renderFile()
#4 /app/vendor/yiisoft/yii2/base/Controller.php(384): yii\web\View->render()
#5 /app/frontend/controllers/shop/CatalogController.php(130): frontend\controllers\shop\CatalogController->render()
#6 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): frontend\controllers\shop\CatalogController->actionProduct()
#7 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#8 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#9 /app/vendor/yiisoft/yii2/base/Module.php(528): frontend\controllers\shop\CatalogController->runAction()
#10 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\web\Application->runAction()
#11 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#12 /app/frontend/web/index.php(17): yii\web\Application->run()
#13 {main}

**Comment by paulzi** [comment]
It is bug of 2.0.14. Please update to 2.0.14.1 and above.

**Comment by LyudmilaPetrova** [comment]
It works. Thanks a lot.
